<!DOCTYPE html>
<html lang="en">
<head>
    <!-- Required meta tags -->
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">

    <link rel="apple-touch-icon" sizes="180x180" href="images/favicon/apple-touch-icon.png">
    <link rel="icon" type="image/png" sizes="32x32" href="images/favicon/favicon-32x32.png">
    <link rel="icon" type="image/png" sizes="16x16" href="images/favicon/favicon-16x16.png">
    <link href="https://fonts.googleapis.com/icon?family=Material+Icons"
          rel="stylesheet">


    <!-- Bootstrap CSS -->
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/css/bootstrap.min.css" integrity="sha384-Gn5384xqQ1aoWXA+058RXPxPg6fy4IWvTNh0E263XmFcJlSAwiGgFAW/dAiS6JXm" crossorigin="anonymous">
    <link rel="stylesheet" href="styles/flowcode.css" type="text/css">

    <title>flowcode</title>
    <style type="text/css" media="screen">
        body {
            overflow: auto;
        }
        #editor {
            margin: 0;
            position: relative;
            top: 0px;
            bottom: 0;
            left: 0;
            right: 0;
            overflow-y: auto;
            height: 80vh;
        }
        .divTable{
            position relative;
            display: table;
            width: 70%;
        }
        .divTableRow {
            display: table-row;
        }

        .divTableCell, .divTableHead {
            display: table-cell;
            padding: 10px 5px;
        }

        .divTableBody {
            display: table-row-group;
        }
        .left {
            border-left:1px solid #999999;
        }
        .right {
            border-right:1px solid #999999;
        }
        .top {
            border-top:1px solid #999999;
        }
        .btm {
            border-bottom:1px solid #999999;
        }
        .material-icons {
            display:none;
        }
        .current {
            display: block;
            color: dodgerblue;
            height: 5px;
            width: 5px;
            padding: 0;
        }

    </style>
</head>

<body>

<nav class="navbar navbar-light bg-light">
    <div class="navbar-brand" href="#">
        <img src="images/logo.png" height="35" class="d-inline-block align-top" alt="">
        <p>
            See how your generated code looks!
        </p>
    </div>
</nav>

<div class="container-fluid">
    <div class="row">
        <div class="col box">
            <div class="row box-heading">
                Enter Generated Code
            </div>
            <div class="row" id="editor" >
                <?php echo $code; ?>
            </div>
            <div class="row">
                <button type="button" class="btn btn-info" id="generate">Poof!</button>
            </div>
        </div>
        <div class="col box">
            <div class="row box-heading">
                Output
            </div>
            <div class="row output">
                ...
            </div>
        </div>
    </div>
</div>
<div class="question">Draw a flowchart to divide a given number A by a given number B.</div>
<br/>
<!--<img src="1/png" id="display" />-->
<div id="display">
    <div class="divTable">
        <div class="divTableBody">
            <div class="divTableRow">
                <div class="divTableCell btm left top">&nbsp;</div>
                <div class="divTableCell btm top">&nbsp;</div>
                <div class="divTableCell btm top">&nbsp;</div>
                <div class="divTableCell btm top">&nbsp;</div>
                <div class="divTableCell btm"><i class="material-icons step0 current">face</i></div>
                <div class="divTableCell btm top">&nbsp;</div>
                <div class="divTableCell top"><i class="material-icons step1">face</i></div>
                <div class="divTableCell top">&nbsp;</div>
                <div class="divTableCell left btm top">&nbsp;</div>
                <div class="divTableCell right top">&nbsp;</div>
            </div>
            <div class="divTableRow">
                <div class="divTableCell left">&nbsp;</div>
                <div class="divTableCell right">&nbsp;</div>
                <div class="divTableCell btm">&nbsp;</div>
                <div class="divTableCell btm">&nbsp;</div>
                <div class="divTableCell"><i class="material-icons step3">face</i></div>
                <div class="divTableCell btm">&nbsp;</div>
                <div class="divTableCell"><i class="material-icons step2">face</i></div>
                <div class="divTableCell btm left">&nbsp;</div>
                <div class="divTableCell">&nbsp;</div>
                <div class="divTableCell right btm">&nbsp;</div>
            </div>
            <div class="divTableRow">
                <div class="divTableCell right left">&nbsp;</div>
                <div class="divTableCell btm">&nbsp;</div>
                <div class="divTableCell right">&nbsp;</div>
                <div class="divTableCell ">&nbsp;</div>
                <div class="divTableCell btm right">&nbsp;</div>
                <div class="divTableCell right">&nbsp;</div>
                <div class="divTableCell right">&nbsp;</div>
                <div class="divTableCell">&nbsp;</div>
                <div class="divTableCell btm">&nbsp;</div>
                <div class="divTableCell right btm">&nbsp;</div>
            </div>
            <div class="divTableRow">
                <div class="divTableCell left btm">&nbsp;</div>
                <div class="divTableCell btm right">&nbsp;</div>
                <div class="divTableCell right">&nbsp;</div>
                <div class="divTableCell right">&nbsp;</div>
                <div class="divTableCell right">&nbsp;</div>
                <div class="divTableCell right">&nbsp;</div>
                <div class="divTableCell right">&nbsp;</div>
                <div class="divTableCell right">&nbsp;</div>
                <div class="divTableCell btm">&nbsp;</div>
                <div class="divTableCell right">&nbsp;</div>
            </div>
            <div class="divTableRow">
                <div class="divTableCell left">&nbsp;</div>
                <div class="divTableCell btm">&nbsp;</div>
                <div class="divTableCell btm"><i class="material-icons step4">face</i></div>
                <div class="divTableCell btm right">&nbsp;</div>
                <div class="divTableCell">&nbsp;</div>
                <div class="divTableCell btm right">&nbsp;</div>
                <div class="divTableCell right">&nbsp;</div>
                <div class="divTableCell right">&nbsp;</div>
                <div class="divTableCell">&nbsp;</div>
                <div class="divTableCell right">&nbsp;</div>
            </div>
            <div class="divTableRow">
                <div class="divTableCell left btm">&nbsp;</div>
                <div class="divTableCell right">&nbsp;</div>
                <div class="divTableCell">&nbsp;</div>
                <div class="divTableCell right">&nbsp;</div>
                <div class="divTableCell btm">&nbsp;</div>
                <div class="divTableCell">&nbsp;</div>
                <div class="divTableCell btm right">&nbsp;</div>
                <div class="divTableCell right">&nbsp;</div>
                <div class="divTableCell right">&nbsp;</div>
                <div class="divTableCell btm right">&nbsp;</div>
            </div>
            <div class="divTableRow">
                <div class="divTableCell left">&nbsp;</div>
                <div class="divTableCell btm right">&nbsp;</div>
                <div class="divTableCell btm right">&nbsp;</div>
                <div class="divTableCell btm">&nbsp;</div>
                <div class="divTableCell right">&nbsp;</div>
                <div class="divTableCell right">&nbsp;</div>
                <div class="divTableCell">&nbsp;</div>
                <div class="divTableCell btm right">&nbsp;</div>
                <div class="divTableCell">&nbsp;</div>
                <div class="divTableCell right">&nbsp;</div>
            </div>
            <div class="divTableRow">
                <div class="divTableCell right left">&nbsp;</div>
                <div class="divTableCell">&nbsp;</div>
                <div class="divTableCell btm">&nbsp;</div>
                <div class="divTableCell right">&nbsp;</div>
                <div class="divTableCell btm">&nbsp;</div>
                <div class="divTableCell btm right">&nbsp;</div>
                <div class="divTableCell right">&nbsp;</div>
                <div class="divTableCell">&nbsp;</div>
                <div class="divTableCell btm right">&nbsp;</div>
                <div class="divTableCell right">&nbsp;</div>
            </div>
            <div class="divTableRow">
                <div class="divTableCell right left">&nbsp;</div>
                <div class="divTableCell"><i class="material-icons step5">face</i></div>
                <div class="divTableCell right">&nbsp;</div>
                <div class="divTableCell btm">&nbsp;</div>
                <div class="divTableCell btm">&nbsp;</div>
                <div class="divTableCell right">&nbsp;</div>
                <div class="divTableCell btm">&nbsp;</div>
                <div class="divTableCell right">&nbsp;</div>
                <div class="divTableCell">&nbsp;</div>
                <div class="divTableCell right btm">&nbsp;</div>
            </div>
            <div class="divTableRow">
                <div class="divTableCell left btm">&nbsp;</div>
                <div class="divTableCell btm right">&nbsp;</div>
                <div class="divTableCell btm">&nbsp;</div>
                <div class="divTableCell btm">&nbsp;</div>
                <div class="divTableCell btm right">&nbsp;</div>
                <div class="divTableCell right"><i class="material-icons step6">face</i></div>
                <div class="divTableCell btm">&nbsp;</div>
                <div class="divTableCell btm right">&nbsp;</div>
                <div class="divTableCell btm">&nbsp;</div>
                <div class="divTableCell btm right">&nbsp;</div>
            </div>
        </div>
    </div>
    <!-- DivTable.com -->
</div>
<br/>
<div id="legend">
    Step 1 <br/>
    Left: Begin <br/>
    Right: Start <br/><br/>
    Step 2 <br/>
    Right: Generate value for A<br/>Down: Accept value for A <br/><br/>
    Step 3 <br/>
    Left: Accept value for B<br/>Down: Calculate Total <br/><br/>
    step 4 <br/>
    Left: Total == A / B<br/>Down: Total = A / B <br/><br/>
    step 5 <br/>
    Left: Print Total<br/>Up: Total == Total <br/><br/>
    step 6 <br/>
    Right: Terminate<br/>Up: End
</div>
<br/>
<button class="steps">Input</button>

<script src="https://ajax.googleapis.com/ajax/libs/jquery/3.3.1/jquery.min.js"></script>
<!-- Optional JavaScript -->
<script src="scripts/src-min-noconflict/ace.js" type="text/javascript" charset="utf-8"></script>
<script>
    var editor = ace.edit("editor");
    editor.setTheme("ace/theme/sqlserver");
    editor.session.setMode("ace/mode/php");
    editor.setShowPrintMargin(false);

    var currentStep = 1;

    $('.steps').click(function () {
        var processStep = new Promise(function (resolve, reject) {
            if (currentStep == 1) {
                $('.step0').removeClass('current');
                $('.step6').addClass('current');
                $('#legend').html("Congrats! You've completed the maze!");
                //$('.step1').addClass('current');
            } else if (currentStep == 2) {
                $('.step1').removeClass('current');
                $('.step2').addClass('current');
            } else if (currentStep == 3) {
                $('.step2').removeClass('current');
                $('.step3').addClass('current');
            } else if (currentStep == 4) {
                $('.step3').removeClass('current');
                $('.step4').addClass('current');
            } else if (currentStep == 5) {
                $('.step4').removeClass('current');
                $('.step5').addClass('current');
            } else if (currentStep == 6) {
                $('.step5').removeClass('current');
                $('.step6').addClass('current');
                $('#legend').html("Congrats! You've completed the maze!");
            }
            resolve();
        });

        // next step
        processStep.then(function(){currentStep += 1});
    });

</script>
<!-- jQuery first, then Popper.js, then Bootstrap JS -->
<script src="https://code.jquery.com/jquery-3.2.1.slim.min.js" integrity="sha384-KJ3o2DKtIkvYIK3UENzmM7KCkRr/rE9/Qpg6aAZGJwFDMVNA/GpGFF93hXpG5KkN" crossorigin="anonymous"></script>
<script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.12.9/umd/popper.min.js" integrity="sha384-ApNbgh9B+Y1QKtv3Rn7W3mgPxhU9K/ScQsAP7hUibX39j7fakFPskvXusvfa0b4Q" crossorigin="anonymous"></script>
<script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/js/bootstrap.min.js" integrity="sha384-JZR6Spejh4U02d8jOt6vLEHfe/JQGiRRSQQxSfFWpi1MquVdAyjUar5+76PVCmYl" crossorigin="anonymous"></script>
</body>
</html>
